### ISSUE TITLE
Broken support of encoding implicit big int since version 0.09

### ISSUE THREAD

**Issue by zhouzhen1** [bricas/math-base36#2]
We use Math-Base36 in our company, and recently we found that starting from version 0.09, the module lost support for encoding implicit big int because of below change (see https://github.com/bricas/math-base36/commit/a1faa1df6641fcdc0b98be7cfe4c6e834a5a5555) in lib/Math/Base36.pm
```diff
-use Math::BigInt qw(:constant);
+use Math::BigInt ();
```
So, if we add a couple of tests into 02-basic.t as below, 
```perl
{
    my $num = '808281277464764060643139600456536293375';
    my $b36 = 'ZZZZZZZZZZZZZZZZZZZZZZZZZ';

    is( decode_base36( $b36 ), $num, 'decode large number (implicit bigint)' );
    is( encode_base36( $num ), $b36, 'encode large number (implicit bigint)' );
}
```
With older versions they are able to pass, but with >=0.09 it would fail like, 
```
t/02-basic.t ......... 1/35
#   Failed test 'encode large number (implicit bigint)'
#   at t/02-basic.t line 50.
#          got: 'ZZZZZZZZZY84KSWGSWO4KSW8O'
#     expected: 'ZZZZZZZZZZZZZZZZZZZZZZZZZ'
# Looks like you failed 1 test of 35.
t/02-basic.t ......... Dubious, test returned 1 (wstat 256, 0x100)
```

This issue caused our code to break when using a recent version of Math::Base36. And we would hope to get back that :constant
Thanks~

**Comment by bricas** [comment]
I chose to explicitly use `Math::BigInt->new` on the input to `encode_base36()` instead of using `:constant` -- the test seems to pass.

Version 0.13 should hit CPAN shortly.

Thanks.
